### ISSUE TITLE
Replace "Try it out!" link

### ISSUE THREAD

**Issue by loklaan** [styled-components/styled-components.github.io#5]
Hey folks! The [current webpackbin link](https://www.webpackbin.com/V1VNoINA-) shouts at the user about the route being old, before redirecting to beta webpackbin.

You could...

* Replace with a new webpackbin ([copying](https://www.webpackbin.com/bins/-KfV2sG35yAfVnBjEBNj) over the code/config works)
* Or ditch webpackbin for glitch.com
  - Has emojis everywhere in it's UI ✨  (haha, styled component project fits in well)
  - Can use create-react-app to bootstrap the 'project'
  - Can attach branding

**Comment by loklaan** [comment]
If you decide to go down the glitch.com rabbit hole, you'll find I've parked on the [~styled-components](https://glitch.com/~styled-components) project url!

**💰 one million dollars💰  ransom**

Joke - I'll give it up.

Again, if you opt for glitch, you can [find some other orgs](https://glitch.com/hello-worlds) that have made branded glitch accounts for hello-world type projects.

**Comment by mxstbr** [comment]
PR to replace it with this link would be appreciated: https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN (taken from the main README)
