### ISSUE TITLE
I cannot access "Try it out" page

### ISSUE THREAD

**Issue by tlakomy** [styled-components/styled-components.github.io#8]
This is a gif I recorded from a while ago, for some reason I cannot access the "try it out" page on styled-components website:

![styled_comps_hd](https://cloud.githubusercontent.com/assets/16646517/24247714/0d58c7f8-0fcd-11e7-9bcc-3f998400f52c.gif)

**Comment by mxstbr** [comment]
Hey! A PR to update the link to https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN would be much appreciated!

**Comment by tlakomy** [comment]
Hey @mxstbr , 

Isn't it already updated in https://github.com/styled-components/styled-components.github.io/blob/dev/src/App.js#L79 ?

**Comment by mxstbr** [comment]
Huh, interesting. Something seems to be off with our domain configuration, I've updated it but I think it needs a new build to show the fixed link?

**Comment by mxstbr** [comment]
Ahh I just needed to manually deploy 🤦‍♂️ should be good in a few minutes, thanks for the issue!
